import '../public/styles/normalize.css'
import '../public/styles/index.scss'
import '../public/styles/proportions.scss'
// import '../public/data'
// import '../public/styles/devices/shared.scss'

import '../public/styles/components/big-video/styles.scss'
import '../public/styles/components/notification/styles.css'
import '../public/styles/components/small-video/styles.scss'
import '../public/styles/components/control-arrows/styles.scss'

import '../public/styles/devices/mobile/header.scss'
import '../public/styles/devices/mobile/main/aside.scss'
import '../public/styles/devices/mobile/main/content.scss'
import '../public/styles/devices/mobile/footer.scss'

import '../public/styles/devices/tablet/header.scss'
import '../public/styles/devices/tablet/main/aside.scss'
import '../public/styles/devices/tablet/main/content.scss'
import '../public/styles/devices/tablet/footer.scss'

import '../public/styles/devices/laptop/header.scss'
import '../public/styles/devices/laptop/main/aside.scss'
import '../public/styles/devices/laptop/main/content.scss'
import '../public/styles/devices/laptop/footer.scss'

import '../public/styles/devices/desktop/header.scss'
import '../public/styles/devices/desktop/main/aside.scss'
import '../public/styles/devices/desktop/main/content.scss'
import '../public/styles/devices/desktop/footer.scss'
